# Generated by Django 3.1.5 on 2021-01-28 14:23

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タグ名')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='背景色')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='サムネイル')),
                ('slug', models.SlugField(unique=True, verbose_name='スラッグ')),
                ('lead_text', models.TextField(max_length=255, verbose_name='紹介文')),
                ('main_text', markdownx.models.MarkdownxField(verbose_name='本文')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開する')),
                ('created_at', models.DateField(verbose_name='作成日')),
                ('color', models.CharField(choices=[('#ffffff', '白'), ('#000000', '黒')], default='#ffffff', max_length=7, verbose_name='文字色')),
                ('tag', models.ManyToManyField(to='blog.Tag', verbose_name='タグ')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
